[target.x86_64-unknown-linux-musl]
linker = "musl-gcc"

[target.aarch64-unknown-linux-musl]
linker = "musl-gcc"

[cargo-new]
name = "fva"
email = "me@nergis.dev"

[registries.crates-io]
protocol = "sparse"

[build]
rustc-wrapper = "sccache"
